CC = gcc -g
CFLAGS = -Wall -Wextra -pedantic -ansi
# LDLIBS = -lodbc

# recompile if this header changes
HEADERS = ./inc/utils.h

EXE = menu
SRCS = src/$(EXE).c src/utils.c
OBJS = $(patsubst src/%, obj/%, $(SRCS:.c=.o))
INC = -I inc
all : $(EXE)


obj/%.o: src/%.c $(HEADERS)
	@echo Compiling $<...
	$(CC) $(CFLAGS) -c -o $@ $< $(INC)

$(EXE): $(DEPS) $(OBJS)
	$(CC) -o $(EXE) $(OBJS) $(LDLIBS) $(INC)

clean :
	rm -f obj/*.o core $(EXE)

fclean: clean
	rm -f menu *.dat *.idx